EMPLOYEES = [
  {"id":"E001","name":"Priya Sharma","gender":"F","current_role":"SDE1","department":"Payments","years_exp":3,"github":"priya-sh","github_url":"https://github.com/priya-sh","linkedin":"https://linkedin.com/in/priya-sharma","email":"priya.sharma@company.com","current_salary":1200000,"tenure_years":2,"skills":["Python","FastAPI","PostgreSQL","Docker","React"],"bio":"Passionate backend engineer with a love for distributed systems and clean APIs. Currently building payment infrastructure at scale.","education":"B.Tech CSE, BITS Pilani (2021)","certifications":["AWS Cloud Practitioner","Docker Certified Associate"],"applied_roles":[],"alerts_enabled":True},
  {"id":"E002","name":"Arjun Mehta","gender":"M","current_role":"SDE1","department":"Search","years_exp":2,"github":"arjun-m","github_url":"https://github.com/arjun-m","linkedin":"https://linkedin.com/in/arjun-mehta","email":"arjun.mehta@company.com","current_salary":1100000,"tenure_years":1,"skills":["Java","Spring Boot","MySQL","Redis","Kafka"],"bio":"Search infrastructure engineer focused on low-latency query systems. Exploring Rust in side projects.","education":"B.Tech CSE, NIT Trichy (2022)","certifications":["Oracle Java SE 11"],"applied_roles":[],"alerts_enabled":True},
  {"id":"E003","name":"Sneha Iyer","gender":"F","current_role":"SDE2","department":"Platform","years_exp":5,"github":"sneha-dev","github_url":"https://github.com/sneha-dev","linkedin":"https://linkedin.com/in/sneha-iyer","email":"sneha.iyer@company.com","current_salary":1800000,"tenure_years":3,"skills":["Go","Kubernetes","Terraform","AWS","Python","gRPC"],"bio":"Platform engineer obsessed with reliability and developer experience. Maintainer of 2 open-source K8s tools.","education":"B.Tech CSE, IIT Bombay (2019)","certifications":["CKA - Certified Kubernetes Administrator","AWS Solutions Architect"],"applied_roles":[],"alerts_enabled":True},
  {"id":"E004","name":"Rahul Verma","gender":"M","current_role":"SDE2","department":"Payments","years_exp":4,"github":"rahulv-code","github_url":"https://github.com/rahulv-code","linkedin":"https://linkedin.com/in/rahul-verma","email":"rahul.verma@company.com","current_salary":1700000,"tenure_years":2,"skills":["Python","Django","PostgreSQL","Celery","Redis","AWS"],"bio":"Full-stack payments engineer with deep expertise in async task processing and financial reconciliation systems.","education":"B.Tech IT, DTU Delhi (2020)","certifications":["AWS Developer Associate"],"applied_roles":[],"alerts_enabled":False},
  {"id":"E005","name":"Ananya Krishnan","gender":"F","current_role":"SDET","department":"QA","years_exp":3,"github":"ananya-k","github_url":"https://github.com/ananya-k","linkedin":"https://linkedin.com/in/ananya-krishnan","email":"ananya.krishnan@company.com","current_salary":1300000,"tenure_years":2,"skills":["Python","Selenium","Pytest","Jenkins","Docker","SQL"],"bio":"QA engineer who believes in shift-left testing. Building automation frameworks that catch bugs before they happen.","education":"B.Tech CSE, VIT Vellore (2021)","certifications":["ISTQB Foundation"],"applied_roles":[],"alerts_enabled":True},
  {"id":"E006","name":"Karan Singh","gender":"M","current_role":"SDE1","department":"ML Platform","years_exp":2,"github":"karan-ml","github_url":"https://github.com/karan-ml","linkedin":"https://linkedin.com/in/karan-singh","email":"karan.singh@company.com","current_salary":1250000,"tenure_years":1,"skills":["Python","PyTorch","Scikit-learn","SQL","Spark"],"bio":"ML engineer passionate about making models production-ready. Kaggle competitions and research papers are weekend hobbies.","education":"B.Tech CSE, IIT Delhi (2022)","certifications":["DeepLearning.AI Deep Learning Specialization"],"applied_roles":[],"alerts_enabled":True},
  {"id":"E007","name":"Divya Nair","gender":"F","current_role":"Tech PM","department":"Growth","years_exp":4,"github":"divya-pm","github_url":"https://github.com/divya-pm","linkedin":"https://linkedin.com/in/divya-nair","email":"divya.nair@company.com","current_salary":2000000,"tenure_years":3,"skills":["Product Strategy","SQL","Jira","Figma","A/B Testing","Python"],"bio":"Technical PM bridging engineering and business. Expert in growth experiments and data-driven product decisions.","education":"B.Tech CSE, IIIT Hyderabad (2020) · MBA pursuing","certifications":["Google Analytics","Pragmatic Institute PMC"],"applied_roles":[],"alerts_enabled":True},
  {"id":"E008","name":"Vikram Bose","gender":"M","current_role":"SDE2","department":"Infrastructure","years_exp":6,"github":"vikram-infra","github_url":"https://github.com/vikram-infra","linkedin":"https://linkedin.com/in/vikram-bose","email":"vikram.bose@company.com","current_salary":2100000,"tenure_years":4,"skills":["Go","Rust","Kubernetes","Terraform","AWS","Linux","gRPC"],"bio":"Infrastructure engineer who has kept systems running at 99.99% uptime. Strong opinions about observability and on-call culture.","education":"B.Tech CSE, IIT Kharagpur (2018)","certifications":["CKA","AWS Solutions Architect Pro","HashiCorp Terraform Associate"],"applied_roles":[],"alerts_enabled":True},
  {"id":"E009","name":"Meera Pillai","gender":"F","current_role":"SDE1","department":"Search","years_exp":2,"github":"meera-p","github_url":"https://github.com/meera-p","linkedin":"https://linkedin.com/in/meera-pillai","email":"meera.pillai@company.com","current_salary":1150000,"tenure_years":1,"skills":["Java","Elasticsearch","MySQL","Python","Spring Boot"],"bio":"Search engineer focused on relevance and ranking algorithms. Loves diving into information retrieval research.","education":"B.Tech CSE, NSIT Delhi (2022)","certifications":["Elastic Certified Engineer"],"applied_roles":[],"alerts_enabled":True},
  {"id":"E010","name":"Aditya Gupta","gender":"M","current_role":"SDE2","department":"Data","years_exp":5,"github":"adi-data","github_url":"https://github.com/adi-data","linkedin":"https://linkedin.com/in/aditya-gupta","email":"aditya.gupta@company.com","current_salary":1900000,"tenure_years":3,"skills":["Python","Spark","Hadoop","Kafka","Airflow","SQL","Scala"],"bio":"Data platform engineer building pipelines that process millions of events daily. Contributor to Apache Spark.","education":"B.Tech CSE, IIIT Bangalore (2019)","certifications":["Databricks Certified Associate","Confluent Kafka Developer"],"applied_roles":[],"alerts_enabled":True},
  {"id":"E011","name":"Ritu Malhotra","gender":"F","current_role":"SDET","department":"Mobile","years_exp":3,"github":"ritu-test","github_url":"https://github.com/ritu-test","linkedin":"https://linkedin.com/in/ritu-malhotra","email":"ritu.malhotra@company.com","current_salary":1350000,"tenure_years":2,"skills":["Appium","Python","Kotlin","Jenkins","Pytest","Postman"],"bio":"Mobile QA specialist ensuring flawless user experiences across iOS and Android. Automation-first mindset.","education":"B.Tech IT, Pune University (2021)","certifications":["ISTQB Agile Tester"],"applied_roles":[],"alerts_enabled":False},
  {"id":"E012","name":"Nikhil Joshi","gender":"M","current_role":"SDE1","department":"ML Platform","years_exp":3,"github":"nikhil-j","github_url":"https://github.com/nikhil-j","linkedin":"https://linkedin.com/in/nikhil-joshi","email":"nikhil.joshi@company.com","current_salary":1300000,"tenure_years":2,"skills":["Python","TensorFlow","SQL","Docker","FastAPI","MLflow"],"bio":"ML platform engineer making model deployment painless. Working on internal feature store and experiment tracking.","education":"B.Tech CSE, VJTI Mumbai (2021)","certifications":["TensorFlow Developer Certificate"],"applied_roles":[],"alerts_enabled":True},
  {"id":"E013","name":"Tanvi Desai","gender":"F","current_role":"SDE2","department":"Payments","years_exp":5,"github":"tanvi-d","github_url":"https://github.com/tanvi-d","linkedin":"https://linkedin.com/in/tanvi-desai","email":"tanvi.desai@company.com","current_salary":1850000,"tenure_years":3,"skills":["Java","Microservices","Kafka","PostgreSQL","AWS","Spring Boot","Docker"],"bio":"Payments backend engineer specialising in microservices and event-driven architectures. PCI DSS compliance expert.","education":"B.Tech CSE, DAIICT (2019)","certifications":["AWS Developer","Spring Professional"],"applied_roles":[],"alerts_enabled":True},
  {"id":"E014","name":"Saurabh Tiwari","gender":"M","current_role":"SDE1","department":"Growth","years_exp":2,"github":"saurabh-t","github_url":"https://github.com/saurabh-t","linkedin":"https://linkedin.com/in/saurabh-tiwari","email":"saurabh.tiwari@company.com","current_salary":1100000,"tenure_years":1,"skills":["React","TypeScript","Node.js","PostgreSQL","GraphQL"],"bio":"Frontend-leaning full-stack engineer building growth experiments and conversion funnels. A/B testing enthusiast.","education":"B.Tech CSE, BIT Mesra (2022)","certifications":["Meta Frontend Developer"],"applied_roles":[],"alerts_enabled":True},
  {"id":"E015","name":"Pooja Saxena","gender":"F","current_role":"Tech PM","department":"Platform","years_exp":6,"github":"pooja-s","github_url":"https://github.com/pooja-s","linkedin":"https://linkedin.com/in/pooja-saxena","email":"pooja.saxena@company.com","current_salary":2400000,"tenure_years":4,"skills":["Product Strategy","Go-to-Market","SQL","Jira","Python","Data Analysis","Stakeholder Mgmt"],"bio":"Senior technical PM with a background in engineering. Shipped 3 major platform migrations and leads the internal developer productivity charter.","education":"B.Tech CSE, IIT Roorkee (2018) · PGP IIM Ahmedabad","certifications":["PMP","Google Project Management"],"applied_roles":[],"alerts_enabled":True},
  {"id":"E016","name":"Harsh Pandey","gender":"M","current_role":"SDE2","department":"Search","years_exp":4,"github":"harsh-p","github_url":"https://github.com/harsh-p","linkedin":"https://linkedin.com/in/harsh-pandey","email":"harsh.pandey@company.com","current_salary":1750000,"tenure_years":2,"skills":["Python","Elasticsearch","Kafka","Redis","AWS","FastAPI"],"bio":"Search platform engineer with expertise in distributed search systems and real-time indexing pipelines.","education":"B.Tech CSE, MNNIT Allahabad (2020)","certifications":["Elastic Certified Engineer","AWS Developer"],"applied_roles":[],"alerts_enabled":True},
  {"id":"E017","name":"Ishita Roy","gender":"F","current_role":"SDE1","department":"Infrastructure","years_exp":2,"github":"ishita-r","github_url":"https://github.com/ishita-r","linkedin":"https://linkedin.com/in/ishita-roy","email":"ishita.roy@company.com","current_salary":1200000,"tenure_years":1,"skills":["Go","Linux","Docker","Python","Bash","Prometheus"],"bio":"Infrastructure engineer who loves systems programming and observability. Building internal developer tooling in Go.","education":"B.Tech CSE, Jadavpur University (2022)","certifications":["Linux Foundation LFCS"],"applied_roles":[],"alerts_enabled":True},
  {"id":"E019","name":"Vamika Mendiratta","gender":"F","current_role":"Talent Intelligence Lead","department":"People & Talent","years_exp":3,"github":"itsvamz","github_url":"https://github.com/itsvamz","linkedin":"https://linkedin.com/in/vamika-mendiratta","email":"vamika.mendiratta1304@gmail.com","current_salary":1800000,"tenure_years":2,"skills":["Python","Data Analysis","Product Strategy","SQL","Stakeholder Mgmt","AI/ML","Community Building"],"bio":"President of 180DC IGDTUW, Director at TEDx, founder of Super30 mentorship community. Passionate about women in tech and building AI-powered talent systems. Currently building TalentIQ at Techkriti × Eightfold AI.","education":"B.Tech CSE (AI), IGDTUW Delhi — Class of 2027 · CGPA 9.36","certifications":["WorldQuant Gold","Google Developer Expert (nominee)","AWS Cloud Practitioner"],"applied_roles":[],"alerts_enabled":True},
  {"id":"E018","name":"Mohit Kapoor","gender":"M","current_role":"SDET","department":"Payments","years_exp":4,"github":"mohit-k","github_url":"https://github.com/mohit-k","linkedin":"https://linkedin.com/in/mohit-kapoor","email":"mohit.kapoor@company.com","current_salary":1400000,"tenure_years":3,"skills":["Python","Selenium","JMeter","Postman","SQL","Jenkins","K6"],"bio":"QA lead for the payments team. Expert in performance testing and building load test frameworks that simulate real traffic.","education":"B.Tech IT, Thapar University (2020)","certifications":["ISTQB Advanced Level","K6 Certified"],"applied_roles":[],"alerts_enabled":True},
]

OPEN_ROLES = [
  {"role_id":"R001","title":"SDE2 — Backend Platform","department":"Platform","required_skills":["Go","Kubernetes","gRPC","PostgreSQL","Docker","AWS"],"nice_to_have":["Terraform","Rust","Prometheus"],"skill_weights":{"Go":3,"Kubernetes":3,"gRPC":2,"PostgreSQL":2,"Docker":1,"AWS":2},"budget_min":1800000,"budget_max":2200000,"external_hire_cost":2500000,"team_composition":{"total":8,"female":1,"male":7},"description":"Own the core backend platform powering all internal microservices. Requires deep Go expertise, Kubernetes cluster management, and gRPC service design.","posted_date":"2024-03-01","urgency":"High"},
  {"role_id":"R002","title":"SDE2 — ML Platform","department":"ML Platform","required_skills":["Python","MLflow","Spark","Docker","Kubernetes","SQL"],"nice_to_have":["TensorFlow","PyTorch","Airflow","Scala"],"skill_weights":{"Python":3,"MLflow":3,"Spark":2,"Docker":2,"Kubernetes":2,"SQL":1},"budget_min":1900000,"budget_max":2300000,"external_hire_cost":2700000,"team_composition":{"total":6,"female":1,"male":5},"description":"Build and maintain the ML model serving infrastructure. Enable data scientists to ship models faster. Own MLflow, feature stores, and batch inference pipelines.","posted_date":"2024-03-05","urgency":"Medium"},
  {"role_id":"R003","title":"SDET — Payments QA Lead","department":"Payments","required_skills":["Python","Selenium","SQL","Postman","Jenkins","Docker"],"nice_to_have":["K6","JMeter","Kafka"],"skill_weights":{"Python":3,"Selenium":3,"SQL":2,"Postman":2,"Jenkins":2,"Docker":1},"budget_min":1500000,"budget_max":1900000,"external_hire_cost":2100000,"team_composition":{"total":5,"female":0,"male":5},"description":"Lead QA strategy for the Payments team. Build automated regression suites, own load testing, and ensure payment flows are bulletproof end-to-end.","posted_date":"2024-03-10","urgency":"High"},
]

GITHUB = {
  "priya-sh":    {"commits_6mo":287,"top_languages":["Python","JavaScript"],"avg_repo_stars":12,"open_source_prs":3,"total_repos":18,"streak_days":94},
  "arjun-m":     {"commits_6mo":134,"top_languages":["Java","Python"],"avg_repo_stars":4,"open_source_prs":0,"total_repos":9,"streak_days":41},
  "sneha-dev":   {"commits_6mo":521,"top_languages":["Go","Python","Shell"],"avg_repo_stars":67,"open_source_prs":12,"total_repos":32,"streak_days":180},
  "rahulv-code": {"commits_6mo":198,"top_languages":["Python","SQL"],"avg_repo_stars":8,"open_source_prs":1,"total_repos":14,"streak_days":60},
  "ananya-k":    {"commits_6mo":176,"top_languages":["Python","JavaScript"],"avg_repo_stars":6,"open_source_prs":2,"total_repos":11,"streak_days":55},
  "karan-ml":    {"commits_6mo":345,"top_languages":["Python","Jupyter"],"avg_repo_stars":31,"open_source_prs":5,"total_repos":22,"streak_days":120},
  "divya-pm":    {"commits_6mo":72, "top_languages":["Python","SQL"],"avg_repo_stars":3,"open_source_prs":0,"total_repos":6,"streak_days":22},
  "vikram-infra":{"commits_6mo":634,"top_languages":["Go","Rust","Shell"],"avg_repo_stars":112,"open_source_prs":23,"total_repos":41,"streak_days":240},
  "meera-p":     {"commits_6mo":112,"top_languages":["Java","Python"],"avg_repo_stars":5,"open_source_prs":0,"total_repos":8,"streak_days":38},
  "adi-data":    {"commits_6mo":402,"top_languages":["Python","Scala"],"avg_repo_stars":44,"open_source_prs":7,"total_repos":27,"streak_days":155},
  "ritu-test":   {"commits_6mo":143,"top_languages":["Python","Kotlin"],"avg_repo_stars":7,"open_source_prs":1,"total_repos":10,"streak_days":48},
  "nikhil-j":    {"commits_6mo":268,"top_languages":["Python","Jupyter"],"avg_repo_stars":22,"open_source_prs":4,"total_repos":19,"streak_days":89},
  "tanvi-d":     {"commits_6mo":314,"top_languages":["Java","Python","Shell"],"avg_repo_stars":29,"open_source_prs":6,"total_repos":21,"streak_days":110},
  "saurabh-t":   {"commits_6mo":167,"top_languages":["TypeScript","JavaScript"],"avg_repo_stars":9,"open_source_prs":1,"total_repos":12,"streak_days":52},
  "pooja-s":     {"commits_6mo":89, "top_languages":["Python","SQL"],"avg_repo_stars":4,"open_source_prs":0,"total_repos":7,"streak_days":28},
  "harsh-p":     {"commits_6mo":231,"top_languages":["Python","Shell"],"avg_repo_stars":14,"open_source_prs":2,"total_repos":16,"streak_days":75},
  "ishita-r":    {"commits_6mo":198,"top_languages":["Go","Python","Shell"],"avg_repo_stars":11,"open_source_prs":2,"total_repos":13,"streak_days":66},
  "mohit-k":     {"commits_6mo":221,"top_languages":["Python","Shell"],"avg_repo_stars":10,"open_source_prs":2,"total_repos":15,"streak_days":73},
}
for emp in EMPLOYEES:
    emp["github_data"] = GITHUB.get(emp["github"], {})

SKILL_ADJACENCY = [
  {"from":"Python","to":"Go","distance":2,"reason":"Systems thinking + type discipline"},
  {"from":"Python","to":"MLflow","distance":1,"reason":"MLflow is Python-native"},
  {"from":"Python","to":"Scala","distance":2,"reason":"Functional paradigm via PySpark"},
  {"from":"Java","to":"Go","distance":2,"reason":"Statically typed, concurrency transfer"},
  {"from":"Docker","to":"Kubernetes","distance":2,"reason":"Container orchestration next step"},
  {"from":"Kubernetes","to":"Terraform","distance":2,"reason":"IaC mindset overlap"},
  {"from":"SQL","to":"Spark","distance":2,"reason":"Spark SQL is a direct superset"},
  {"from":"FastAPI","to":"gRPC","distance":2,"reason":"Service design principles transfer"},
  {"from":"PyTorch","to":"TensorFlow","distance":2,"reason":"Deep learning fundamentals identical"},
  {"from":"AWS","to":"GCP","distance":2,"reason":"Cloud fundamentals transfer 1-to-1"},
  {"from":"Go","to":"Rust","distance":2,"reason":"Systems languages, memory model"},
  {"from":"Spark","to":"Airflow","distance":2,"reason":"Both data orchestration tools"},
]
LEARNING_WEEKS = {1: 2, 2: 5, 3: 12}

COURSES = {
  "Go":{"course":"Go: The Complete Developer's Guide","platform":"Udemy","weeks":4,"cost":499,"url":"https://udemy.com/course/go-the-complete-developers-guide"},
  "Kubernetes":{"course":"Kubernetes for Absolute Beginners","platform":"Udemy","weeks":3,"cost":499,"url":"https://udemy.com/course/learn-kubernetes"},
  "Terraform":{"course":"HashiCorp Terraform Associate Prep","platform":"freeCodeCamp","weeks":2,"cost":0,"url":"https://youtube.com/watch?v=SPcwo0Gq9T8"},
  "gRPC":{"course":"gRPC Master Class with Go","platform":"Udemy","weeks":2,"cost":499,"url":"https://udemy.com/course/grpc-golang"},
  "MLflow":{"course":"MLflow in Action","platform":"LinkedIn Learning","weeks":1,"cost":1500,"url":"https://linkedin.com/learning/mlflow-in-action"},
  "Spark":{"course":"Apache Spark with Python","platform":"Udemy","weeks":4,"cost":499,"url":"https://udemy.com/course/pyspark-and-apache-spark"},
  "Rust":{"course":"Ultimate Rust Crash Course","platform":"Udemy","weeks":5,"cost":499,"url":"https://udemy.com/course/ultimate-rust-crash-course"},
  "Kafka":{"course":"Apache Kafka for Beginners","platform":"Udemy","weeks":3,"cost":499,"url":"https://udemy.com/course/apache-kafka"},
  "Docker":{"course":"Docker and Kubernetes: Complete Guide","platform":"Udemy","weeks":3,"cost":499,"url":"https://udemy.com/course/docker-and-kubernetes-the-complete-guide"},
  "Selenium":{"course":"Selenium WebDriver with Python","platform":"Udemy","weeks":3,"cost":499,"url":"https://udemy.com/course/selenium-real-time-examples"},
  "PostgreSQL":{"course":"SQL and PostgreSQL: Complete Guide","platform":"Udemy","weeks":3,"cost":499,"url":"https://udemy.com/course/sql-and-postgresql"},
  "AWS":{"course":"AWS Solutions Architect — freeCodeCamp","platform":"YouTube","weeks":6,"cost":0,"url":"https://youtube.com/watch?v=Ia-UEYYR44s"},
  "SQL":{"course":"SQL for Data Science","platform":"Coursera","weeks":3,"cost":0,"url":"https://coursera.org/learn/sql-for-data-science"},
  "Postman":{"course":"Postman: The Complete Guide","platform":"Udemy","weeks":1,"cost":499,"url":"https://udemy.com/course/postman-the-complete-guide"},
  "Jenkins":{"course":"Jenkins Beginner to Pro","platform":"Udemy","weeks":2,"cost":499,"url":"https://udemy.com/course/jenkins-from-zero-to-hero"},
  "TensorFlow":{"course":"TensorFlow Developer Certificate","platform":"Coursera","weeks":6,"cost":0,"url":"https://coursera.org/professional-certificates/tensorflow-in-practice"},
  "Prometheus":{"course":"Prometheus & Grafana: Complete Guide","platform":"YouTube","weeks":1,"cost":0,"url":"https://youtube.com/watch?v=h4Sl21AKiDg"},
  "Airflow":{"course":"Complete Hands-On Apache Airflow","platform":"Udemy","weeks":3,"cost":499,"url":"https://udemy.com/course/the-complete-hands-on-course-to-master-apache-airflow"},
  "Scala":{"course":"Functional Programming in Scala","platform":"Coursera","weeks":8,"cost":0,"url":"https://coursera.org/specializations/scala"},
}
